name: pihole
services:
  pihole:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      #- "67:67/udp" # DHCP Server
    environment:
      TZ: 'Europe/London'
      FTLCONF_webserver_api_password: 'Pineapples'
      FTLCONF_dns_upstreams: 1.1.1.1;1.0.0.1;8.8.8.8;8.8.4.4
    volumes:
      - './config:/etc/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    container_name: pihole
    image: pihole/pihole:latest
