name: tailscale
services:
  tailscale:
    environment:
      - TS_AUTH_ONCE=true
      - TS_HOSTNAME=wifi-pwn
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --advertise-exit-node --ssh
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    volumes:
      - ./tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    hostname: tailscale
    image: tailscale/tailscale:latest
